name: Angular Build
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install and run build
        # Runs a set of commands using the runners shell
        run: |
          # npm install yarn
          # todo: delete lock file
          yarn install
          yarn run build:prod

      #create new tag only on push event
      - name: Bump version and push tag
        id: tag_version
        if: ${{ github.event_name == 'push' }}
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.TOKEN }}

      #create new release only on push event
      - name: Push Build to Releases
        if: ${{ github.event_name == 'push' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/pull-request-notifications/*"
          token: ${{ secrets.TOKEN }}
          commit: master
          tag: ${{ steps.tag_version.outputs.new_tag }}
